// ============================================================
// SafeGuard OSINT — Mock Data
// ============================================================

export const mockUser = {
  name: "Rafael Mendes",
  email: "rafael.mendes@empresa.com",
  avatar: "RM",
  plan: "Professional",
  exposureScore: 42,
  lastScan: "2 horas atrás",
};

export const mockStats = {
  exposureScore: 42,
  riskLevel: "Médio",
  leaksFound: 7,
  monitoredItems: 12,
  lastScan: "01/06/2026 às 21:34",
  resolvedIssues: 3,
  criticalAlerts: 2,
};

export const mockExposureTrend = [
  { date: "Jan", score: 68 },
  { date: "Fev", score: 72 },
  { date: "Mar", score: 65 },
  { date: "Abr", score: 58 },
  { date: "Mai", score: 51 },
  { date: "Jun", score: 42 },
];

export const mockRiskDistribution = [
  { name: "Crítico", value: 2, color: "#ef4444" },
  { name: "Alto", value: 3, color: "#f97316" },
  { name: "Médio", value: 5, color: "#eab308" },
  { name: "Baixo", value: 8, color: "#22c55e" },
];

export const mockFindings = [
  {
    id: "1",
    type: "E-mail",
    source: "HaveIBeenPwned",
    data: "rafael.mendes@empresa.com",
    date: "28/05/2026",
    risk: "critical" as const,
    status: "open" as const,
    description: "E-mail encontrado em vazamento do LinkedIn (2024)",
  },
  {
    id: "2",
    type: "Senha Hash",
    source: "BreachDirectory",
    data: "bcrypt:$2a$10$...",
    date: "25/05/2026",
    risk: "critical" as const,
    status: "open" as const,
    description: "Hash de senha exposta em banco de dados comprometido",
  },
  {
    id: "3",
    type: "Telefone",
    source: "Truecaller Leak",
    data: "+55 11 9****-4521",
    date: "20/05/2026",
    risk: "high" as const,
    status: "open" as const,
    description: "Número de telefone associado a nome completo em banco público",
  },
  {
    id: "4",
    type: "CPF",
    source: "Fórum Darkweb",
    data: "***.***.***-**",
    date: "15/05/2026",
    risk: "high" as const,
    status: "in_progress" as const,
    description: "CPF mencionado em thread de venda de dados",
  },
  {
    id: "5",
    type: "Endereço",
    source: "Google Dorks",
    data: "Rua das Flores, 123...",
    date: "10/05/2026",
    risk: "medium" as const,
    status: "open" as const,
    description: "Endereço residencial indexado em site de imóveis",
  },
  {
    id: "6",
    type: "Username",
    source: "Sherlock",
    data: "@rmendes",
    date: "05/05/2026",
    risk: "medium" as const,
    status: "resolved" as const,
    description: "Username encontrado em 14 plataformas diferentes",
  },
  {
    id: "7",
    type: "Foto",
    source: "PimEyes",
    data: "3 correspondências",
    date: "01/05/2026",
    risk: "low" as const,
    status: "resolved" as const,
    description: "Fotos de perfil encontradas em sites de terceiros",
  },
];

export const mockMonitoredItems = [
  {
    id: "1",
    type: "email",
    label: "E-mail Principal",
    value: "rafael.mendes@empresa.com",
    status: "active",
    alerts: 2,
    lastCheck: "2h atrás",
  },
  {
    id: "2",
    type: "cpf",
    label: "CPF",
    value: "***.***.***-**",
    status: "active",
    alerts: 1,
    lastCheck: "2h atrás",
  },
  {
    id: "3",
    type: "phone",
    label: "Telefone",
    value: "+55 11 9****-4521",
    status: "active",
    alerts: 1,
    lastCheck: "2h atrás",
  },
  {
    id: "4",
    type: "username",
    label: "Username",
    value: "@rmendes",
    status: "active",
    alerts: 0,
    lastCheck: "2h atrás",
  },
  {
    id: "5",
    type: "domain",
    label: "Domínio",
    value: "empresa.com",
    status: "active",
    alerts: 0,
    lastCheck: "2h atrás",
  },
];

export const mockAlerts = [
  {
    id: "1",
    category: "leak" as const,
    title: "Novo vazamento detectado",
    description: "Seu e-mail foi encontrado em novo vazamento do serviço Dropbox (2026).",
    time: "Há 2 horas",
    read: false,
    severity: "critical" as const,
  },
  {
    id: "2",
    category: "discovery" as const,
    title: "Nova descoberta: Senha hash",
    description: "Hash de senha identificado em banco de dados comprometido no BreachDirectory.",
    time: "Há 5 horas",
    read: false,
    severity: "critical" as const,
  },
  {
    id: "3",
    category: "recommendation" as const,
    title: "Recomendação: Ativar 2FA",
    description: "Detectamos que sua conta não possui autenticação de dois fatores ativa em 3 serviços.",
    time: "Há 1 dia",
    read: false,
    severity: "high" as const,
  },
  {
    id: "4",
    category: "discovery" as const,
    title: "Telefone encontrado em base pública",
    description: "Seu número foi associado ao seu nome completo no Truecaller.",
    time: "Há 2 dias",
    read: true,
    severity: "high" as const,
  },
  {
    id: "5",
    category: "update" as const,
    title: "Varredura concluída",
    description: "Varredura semanal finalizada. 7 itens monitorados verificados com sucesso.",
    time: "Há 3 dias",
    read: true,
    severity: "low" as const,
  },
  {
    id: "6",
    category: "recommendation" as const,
    title: "Recomendação: Trocar senha",
    description: "A senha associada ao seu e-mail principal pode ter sido comprometida.",
    time: "Há 4 dias",
    read: true,
    severity: "medium" as const,
  },
];

export const mockMitigationGuides = [
  {
    id: "1",
    category: "Senhas",
    title: "Troca de Senha Comprometida",
    description: "Sua senha foi exposta em um vazamento de dados. É necessário trocar imediatamente em todos os serviços onde ela é utilizada.",
    risk: "critical" as const,
    status: "pending" as const,
    steps: [
      "Acesse o gerenciador de senhas (ex: Bitwarden, 1Password)",
      "Gere uma nova senha forte com pelo menos 16 caracteres",
      "Atualize a senha em todos os serviços afetados",
      "Ative autenticação de dois fatores (2FA) em cada serviço",
      "Verifique sessões ativas e encerre as suspeitas",
    ],
    links: [
      { label: "Bitwarden", url: "https://bitwarden.com" },
      { label: "HaveIBeenPwned", url: "https://haveibeenpwned.com" },
    ],
    estimatedTime: "30 min",
  },
  {
    id: "2",
    category: "E-mail",
    title: "Remoção de E-mail de Bases de Dados",
    description: "Seu e-mail está indexado em diversas bases de dados públicas e de marketing. Solicitar remoção reduz o risco de phishing.",
    risk: "high" as const,
    status: "in_progress" as const,
    steps: [
      "Acesse o site opt-out de cada serviço de marketing",
      "Solicite remoção via LGPD/GDPR quando aplicável",
      "Use o serviço DeleteMe ou similar para automação",
      "Monitore por 30 dias para confirmar remoção",
    ],
    links: [
      { label: "DeleteMe", url: "https://joindeleteme.com" },
      { label: "Portal ANPD", url: "https://www.gov.br/anpd" },
    ],
    estimatedTime: "2 horas",
  },
  {
    id: "3",
    category: "Redes Sociais",
    title: "Auditoria de Privacidade nas Redes Sociais",
    description: "Suas contas em redes sociais podem estar com configurações de privacidade inadequadas, expondo informações pessoais.",
    risk: "medium" as const,
    status: "pending" as const,
    steps: [
      "Revise as configurações de privacidade no Instagram, Facebook e LinkedIn",
      "Remova informações sensíveis do perfil público (telefone, endereço)",
      "Restrinja quem pode ver suas publicações antigas",
      "Revogue permissões de aplicativos de terceiros",
    ],
    links: [
      { label: "Privacy Checkup - Facebook", url: "https://facebook.com/privacy/checkup" },
      { label: "LinkedIn Privacy", url: "https://linkedin.com/psettings" },
    ],
    estimatedTime: "1 hora",
  },
  {
    id: "4",
    category: "Documentos",
    title: "Proteção de CPF",
    description: "Seu CPF foi encontrado em bases de dados. Registre um boletim de ocorrência e monitore seu crédito.",
    risk: "high" as const,
    status: "pending" as const,
    steps: [
      "Registre BO online na delegacia virtual do seu estado",
      "Consulte e monitore seu CPF no Serasa e SPC",
      "Ative o alerta de crédito no Serasa",
      "Verifique se há dívidas ou contratos em seu nome",
      "Considere o bloqueio preventivo do CPF na Receita Federal",
    ],
    links: [
      { label: "Serasa", url: "https://serasa.com.br" },
      { label: "Receita Federal", url: "https://receita.economia.gov.br" },
    ],
    estimatedTime: "45 min",
  },
  {
    id: "5",
    category: "Dispositivos",
    title: "Ativação de Autenticação de Dois Fatores",
    description: "Contas sem 2FA são altamente vulneráveis após um vazamento de senha.",
    risk: "medium" as const,
    status: "completed" as const,
    steps: [
      "Instale um autenticador (Google Authenticator, Authy)",
      "Ative 2FA em e-mail, redes sociais e serviços financeiros",
      "Salve os códigos de recuperação em local seguro",
      "Prefira TOTP (app) em vez de SMS quando possível",
    ],
    links: [
      { label: "Authy", url: "https://authy.com" },
      { label: "2FA Directory", url: "https://2fa.directory" },
    ],
    estimatedTime: "20 min",
  },
];

export const mockReportData = {
  scoreHistory: [
    { month: "Jan/26", score: 68, leaks: 12 },
    { month: "Fev/26", score: 72, leaks: 14 },
    { month: "Mar/26", score: 65, leaks: 11 },
    { month: "Abr/26", score: 58, leaks: 9 },
    { month: "Mai/26", score: 51, leaks: 8 },
    { month: "Jun/26", score: 42, leaks: 7 },
  ],
  heatmapData: [
    { day: "Seg", hour: "08h", value: 2 },
    { day: "Seg", hour: "14h", value: 5 },
    { day: "Ter", hour: "10h", value: 3 },
    { day: "Qua", hour: "16h", value: 7 },
    { day: "Qui", hour: "09h", value: 1 },
    { day: "Sex", hour: "15h", value: 4 },
  ],
  timeline: [
    { date: "01/06/2026", event: "Novo vazamento: Dropbox", severity: "critical" },
    { date: "28/05/2026", event: "Varredura semanal concluída", severity: "info" },
    { date: "25/05/2026", event: "Senha hash detectada", severity: "critical" },
    { date: "20/05/2026", event: "Telefone em base pública", severity: "high" },
    { date: "15/05/2026", event: "CPF em fórum darkweb", severity: "high" },
    { date: "10/05/2026", event: "Endereço indexado", severity: "medium" },
    { date: "05/05/2026", event: "Username mapeado", severity: "medium" },
    { date: "01/05/2026", event: "Fotos encontradas", severity: "low" },
  ],
};
